app/ui/routes/auth.py
import datetime
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    request,
    flash
)
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
# external imports
import app.bl.user_controller as uc

bp = Blueprint('auth', __name__)


@bp.route('/login', methods=['GET'])
def login():
    if current_user.is_authenticated:
        return redirect('/map')
    else:
        return render_template('login.html')


@bp.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = bool(request.form.get('remember'))

    user = uc.get_user_by_email(email)

    if not user or not check_password_hash(user.Hash, password):
        flash('Please check your login details and try again.', 'danger')
        return redirect(url_for('auth.login'))

    login_user(user, remember=remember)
    uc.add_user_token(user)

    flash(f'Logged in as {user.Username}', 'success')
    return redirect('/map')


@bp.route('/signup', methods=['GET'])
def signup():
    return render_template('signup.html')


@bp.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('Email')
    username = request.form.get('Username')
    password = request.form.get('Password')

    user = uc.get_user_by_email(email)

    if user:
        flash('Email address already exists.', 'danger')
        return redirect(url_for('auth.signup'))

    new_user = {
        'Email': email,
        'Username': username,
        'Hash': generate_password_hash(password, method='sha256', salt_length=32),
        'JoinDate': datetime.date.today(),
        'PermissionLevel': 1
    }
    flash('Signup successfull', 'success')

    uc.add_user(new_user)
    return redirect('/login')


@bp.route('/logout', methods=['GET'])
@login_required
def logout():
    uc.remove_user_token(current_user)
    logout_user()
    flash('Logging out', 'neutral')
    return redirect('/map')

app/ui/routes/map.py
from flask import Blueprint, render_template, request
from flask_login import current_user
import app.bl.location_controller as lc
import app.bl.utility_controller as uc
from app.utils import make_list_of_dicts_jsonable, make_dict_jsonable
bp = Blueprint('map', __name__, url_prefix='/map')


@bp.route('/')
def index():
    locations = lc.get_all_locations()
    location_dicts = uc.rows_to_dicts(locations)
    location_dicts = make_list_of_dicts_jsonable(location_dicts)
    location_id = request.args.get('location_id')
    location_id = location_id if location_id else None
    jinja_dict = {
        'locations': location_dicts,
        'location_id': location_id,
    }
    if current_user.is_authenticated:
        user_dict = uc.row_to_dict(current_user)
        user_dict = make_dict_jsonable(user_dict)
        jinja_dict['user'] = user_dict

    return render_template('map.html', **jinja_dict)

app/ui/routes/place.py
from flask import Blueprint, render_template
import app.bl.location_controller as lc

bp = Blueprint('place', __name__, url_prefix='/place')


@bp.route('/')
def place():
    location = lc.get_location("")

    return render_template(
        'place_name.html', location=location)


@bp.route('/<name>')
def place_name(name):
    location = lc.get_location(name)

    return render_template(
        'place_name.html', location=location)

app/ui/routes/profile.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
import app.bl.utility_controller as uc
from app.utils import make_dict_jsonable
bp = Blueprint('profile', __name__, url_prefix='/profile')


@bp.route('/')
@login_required
def index():
    print(current_user)
    user_dict = uc.row_to_dict(current_user)
    user_dict = make_dict_jsonable(user_dict)
    return render_template('profile.html', user=user_dict)

app/ui/templates/ground.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>GeoGallery</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/ground.css')}}" />
    {% endblock %}
</head>
<body>
    <div id="top-bar">
        <a id="home" href="{{ url_for('map.index') }}">HAM GeoGallery</a>
        <div class="spacer">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages and request.endpoint not in ('auth.login', 'auth.signup') %}
                    <div class="info {{ messages[0][0] }}">
                        {{ messages[0][1] }}
                    </div>
                {% endif %}
            {% endwith %}
        </div>
        <a class="top-bar-item" href="{{ url_for('map.index') }}">Map</a>
        <a class="top-bar-item" href="{{ url_for('place.place') }}">Places</a>

        {% if current_user.is_authenticated %}
            <a class="top-bar-item" href="{{ url_for('profile.index') }}">Profile</a>
            <a class="top-bar-item" href="{{ url_for('auth.logout') }}">logout</a>
        {% else %}
            <a class="top-bar-item" href="{{ url_for('auth.login') }}">Login</a>
            <a class="top-bar-item" href="{{ url_for('auth.signup') }}">Sign Up</a>
        {% endif %}
    </div>
    {% block content %}{% endblock %}
</body>
</html>

app/ui/templates/login.html
{% extends "ground.html" %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/auth.css' )}}" />
{% endblock %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="notification is-{{ messages[0][0] }}">
                {{ messages[0][1] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" value="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

app/ui/templates/map.html
{% extends "ground.html" %}
{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/map/main.css')}}" />
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/map/sidebar.css')}}" />
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/map/map.css')}}">
<script src="https://kit.fontawesome.com/97cec024a4.js" crossorigin="anonymous"></script>
<script src="{{ url_for('static', filename='js/map/utils.js')}}" type="module"></script>
<script src="{{ url_for('static', filename='js/map/config.js')}}" type="module"></script>
<script src="{{ url_for('static', filename='js/map/api.js')}}" type="module"></script>
<script src="{{ url_for('static', filename='js/map/sidebar.js')}}" type="module"></script>
<script>
    let locations = {{ locations | tojson }};
    let user = null;
    {% if user is defined %}
        user = {{ user | tojson }};
    {% endif %}
    let location_id = null;
    {% if location_id is not none %}
        location_id = {{ location_id }}
    {% endif %}
</script>
<script src="{{ url_for('static', filename='js/map/map.js') }}" type="module"></script>
{% endblock %}

{% block content %}
<div id="container">
    <div id="sidebar"></div>
    <div id="map"></div>
</div>
{% endblock %}

app/ui/templates/place_name.html
{% extends "ground.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/place.css')}}" />
{% endblock %}
{% block content %}
    <div id="content">
        <div id="container">
            <div class="scroll_left">
                {% for loc in location %}
                    <div class="place_box">
                        <div class="align_center"><a href="../map?location_id={{ loc.Id }}"><b>{{loc.Place}}</b></a></div>
                    </div>
                    <div id="rev_box">
                        {% for r in loc.review %}
                            <div class="top_margin">
                                <div class="align_center" font-size="20px"><a>{{r.Title}}</a></div>

                                <div class="box"><revtext>{{r.ReviewText}}</revtext></div>
                                <div id="myProgress"><div id="myBar"style="width:calc({{r.Score}}% * 10)"></div></div>
                                <div class="username"><user>{{r.user.Username}}</user></div>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>

            <div class="scroll_right">
                {% for loc in location %}
                    <div class="align_center "><p class="place_box" style="margin-bottom: 0px;"><a><b>{{loc.Place}}</b></a></p></div>
                    <div class="align_center">
                        <div class="pic_box" style="margin-left: 5%; margin-right: 5%">
                            {% for p in loc.picture %}
                                <a><imag><img src="http://127.0.0.1:5000/api/static/image/{{p.FileName}}" width="200" height="200"></imag></a>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

app/ui/templates/profile.html
{% extends "ground.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/profile.css')}}" />
    <script src="{{ url_for('static', filename='js/functions.js')}}" type="module"></script>
    <script src="{{ url_for('static', filename='js/profile.js')}}" type="module"></script>
{% endblock %}
{% block content %}
    <div id="content">
        <div class="container">
            <div class="header">Profile for {{ current_user.Username }}</div>
            <div class="info-container">
                <div class="left-infobox">
                    <div class="box-header">User Information</div>
                    <form id="user-form">
                        <div class="general-box">
                            <div class="general-box-left">
                                <label>Firstname</label>
                                <label>Lastname</label>
                                <label>Email</label>
                                <label>Username</label>
                                <label>Phone</label>
                                <label>Date of birth</label>
                                <label>Join Date</label>
                            </div>
                            <div class="general-box-right">
                                <input name="user_id" type="hidden" value="{{ current_user.Id }}"/>
                                <input name="token" type="hidden" value="{{ current_user.Token }}"/>
                                <input name="first_name" type="text" value="{{ current_user.FirstName }}"/>
                                <input name="last_name" type="text" value="{{ current_user.LastName }}"/>
                                <input name="email" type="email" value="{{ current_user.Email }}"/>
                                <input name="username" type="text" value="{{ current_user.Username }}"/>
                                <input name="phone" type="text" value="{{ current_user.PhoneNumber }}"/>
                                <input name="date_of_birth" type="date" value="{{ current_user.DateOfBirth }}"/>
                                <input type="date" disabled value="{{ current_user.JoinDate }}"/>
                            </div>
                        </div>
                        <button>Submit changes</button>
                    </form>
                </div>
                <div class="right-infobox">
                    <div class="image-box">
                        <div class="box-header">Badge</div>

                    </div>
                    <div class="stats-box">
                        <div class="box-header">Stats</div>

                    </div>

                </div>

            </div>
        </div>
    </div>
{% endblock %}

app/ui/templates/signup.html
{% extends "ground.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/auth.css' )}}" />
{% endblock %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <label class="label">E-mail
                        <input class="input is-large" type="email" name="Email" placeholder="Your Email" autofocus="">
                    </label>
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <label class="label">Username
                        <input class="input is-large" type="name" name="Username" placeholder="Your User Name" autofocus="">
                    </label>
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <label class="label">Password
                        <input class="input is-large" type="password" name="Password" placeholder="Your Password">
                    </label>
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock content %}